### ISSUE TITLE
correct sunrise/sunset for atmospheric pressure

### ISSUE THREAD

**Issue by dmd** [dferrante/pywx#2]
Someone (maybe even me) should correct forecast.io's sunrise/sunset times for local atmospheric pressure.

I confirmed with forecast.io that they do not do this correction.

Code to do it is in GNU Gcal, `rc-astro.c`, function `atmospheric_refraction(altitude, pressure, temperature)`.

**Comment by dmd** [comment]
Failing to do this means the time of sunset/sunrise can be wrong by several seconds!

**Comment by dziban303** [comment]
Did you ever do anything with this?

**Comment by dmd** [comment]
No and I'm not going to.
